[package]
name = "searchfox-rustc-analyser"
version = "0.1.0"
authors = ["Emilio Cobos √Ålvarez <emilio@crisal.io>"]

[dependencies]
rls-analysis = "0.8"
rls-data = "0.12"
clap = "2"
serde = "1"
serde_json = "1"
